# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/date.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/date.proto", :syntax => :proto3) do
    add_message "date.Date" do
      optional :year, :int32, 1
      optional :month, :int32, 2
      optional :day, :int32, 3
    end
  end
end

module Date
  Date = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("date.Date").msgclass
end
