# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/employee.proto

require 'google/protobuf'

require 'proto/date_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/employee.proto", :syntax => :proto3) do
    add_message "employee.Employee" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :email, :string, 3
      optional :occupation, :enum, 4, "employee.Occupation"
      repeated :phone_number, :string, 5
      map :project, :string, :message, 6, "employee.Company.Project"
      optional :birthday, :message, 9, "date.Date"
      oneof :profile do
        optional :text, :string, 7
        optional :video, :message, 8, "employee.Video"
      end
    end
    add_message "employee.Company" do
    end
    add_message "employee.Company.Project" do
    end
    add_message "employee.Video" do
    end
    add_enum "employee.Occupation" do
      value :OCCUPATION_UNKNOWN, 0
      value :ENGINEER, 1
      value :DESIGNER, 2
      value :MANAGER, 3
    end
  end
end

module Employee
  Employee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Employee").msgclass
  Company = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Company").msgclass
  Company::Project = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Company.Project").msgclass
  Video = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Video").msgclass
  Occupation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("employee.Occupation").enummodule
end
